# Dependencies
plugins:             [jekyll-paginate]
markdown:            kramdown
kramdown:
   math_engine: mathjax
highlighter:         pygments.rb

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true
future: true

# Setup
title:               Burak Aktas
tagline:             'Software Engineer'
description:         All about programming
url:                 http://buraktas.com
baseurl:             /
paginate:            5
excerpt_separator: <!--more-->

# About/contact
author:
  name:              Burak Aktas
  email:             buraktas@gmail.com
  linkedin:          burakaktas
#  url:               https://twitter.com/mdo

# Custom vars
version:             1.0.0
